# @TODO: For some reason ftp folder doesnt get created

version: "3"
services: 
    node:
        container_name: node
        image: node:14
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
        command: "npm run dev"
        environment: 
            PGHOST: postgres
            PGUSER: postgres
            PGDATABASE: postgres
            PGPASSWORD: 'example'
            PGPORT: 5432
    ftpd_server:
        image: stilliard/pure-ftpd
        container_name: pure-ftpd
        volumes:
            - "./ftp/data:/home/admin/"
        environment:
            PUBLICHOST: "localhost"
            FTP_USER_NAME: admin
            FTP_USER_PASS: password123456
            FTP_USER_HOME: /home/admin
            restart: always
    nginx:
        image: nginx
        container_name: nginx
        ports: 
            - "80:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d/
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        user: postgres
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_DB: example_db
        volumes:
            - ./postgres/data:/var/lib/postgresql/data


  
        